### ISSUE TITLE
Fix SELinux context for non-standard httpd conf files

### ISSUE THREAD

**Issue by mnagy** [openshift/sti-perl#14]
From https://github.com/sclorg/rhscl2dockerfile/issues/19#issuecomment-105499125:

> The dockerfile as well as .sti/bin/run script moves httpd files to non-default path (/opt/openshift). Without tuning selinux file labeling, it will cause SELinux denials preventing httpd from accessing the files. Either you should use the default directories, or amend SELinux file contexts (semanage fcontext --add && restorecon -FR), or disable SELinux. (I do not recomend the last option, I prefer the first one).

I think that the best and quickest fix would be to amend the SELinux file contexts in the Dockerfile.

**Comment by ppisar** [comment]
Do we wait on user name space support in Docker?

**Comment by bparees** [comment]
@mnagy is this still an issue?  i'm able to use host content out of this image with selinux enabled....

**Comment by bparees** [comment]
@mnagy bump

**Comment by ppisar** [comment]
Being able to use it and having it secured are two independent questions. Originally there was no SELinux context. Then the policy changed so that all processes running inside one container have the same SELinux label. That's improvement, but comparing to normal system, there is no separation inside the container. I do not know if this is the desired behavior. Probably it is and you can close this issue. But that's not a question I can answer. Probably people from security team or a security architect for Docker/OpenShift should know.
