### ISSUE TITLE
CPAN modules that require non-base system libs are not supported

### ISSUE THREAD

**Issue by nhr** [openshift/sti-perl#68]
I attempted to create a Perl-based image from an application that requires the [GD](http://search.cpan.org/~lds/GD-2.56/) module, which depends upon [libgd](http://libgd.github.io/). I tried using the perl-516-centos7 s2i image for this purpose.

The `cpanm` approach to adding and building modules failed due to the absence of the [gd-devel](http://rpmfind.net/linux/rpm2html/search.php?query=gd-devel&submit=Search+...&system=centos&arch=x86_64) RPM in the builder, but this problem also exists in the resulting image. In the output below, you can see that even if I use `cpanm` on a CentOS 7 host to build and vendor-ize the GD module into my source repo, it still fails for lack of the needed libraries:

```
bash-4.2$ ldd /opt/app-root/src/Vendor/lib/perl5/x86_64-linux-thread-multi/auto/GD/GD.so
	linux-vdso.so.1 =>  (0x00007ffdfcc48000)
	libXpm.so.4 => not found
	libX11.so.6 => not found
	libjpeg.so.62 => not found
	libfontconfig.so.1 => not found
	libfreetype.so.6 => not found
	libpng15.so.15 => not found
	libz.so.1 => /lib64/libz.so.1 (0x00007fbfb6b2b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fbfb6828000)
	libgd.so.2 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007fbfb6467000)
	/lib64/ld-linux-x86-64.so.2 (0x0000560035716000)
```

Many of the CPAN modules depend upon system libraries in order to function properly, and currently there is no way to specify RPMs that must be installed - both in the build environment and the completed image - to enable these modules to function.

One possible solution may be to specify a named file (similar to the `cpanfile`) where devs can list the RPMs that are required by their CPAN modules.

**Comment by ppisar** [comment]
That's great idea and I know about this deficiency. But It's common problem for all images and I'd like to see the same API (e.g. a file name and its format) in all other CentoOS-based images. And also there is a possibility that it will not work in OpenShift image builder because it would require root privilege when building an application image from an s2i-ready base image and that's not allowed for security reasons. At least I think it's so.

@mfojitk, what's your opinion?

**Comment by mfojtik** [comment]
@ppisar @nhr the problem is that we run assemble as non-root user, so we won't be able to install the packages you specify in the file. The solution for this today is that you have to create your own Docker image with all dependencies installed. If we get many requests to add gd lib we should install it in the base image. @bparees right?

**Comment by bparees** [comment]
@mfojtik +1

btw @nhr I suggest you use the centos/perl-520-centos7 image instead, just for currency reasons.

**Comment by ppisar** [comment]
Docker 1.10 can do user name spacing. Finally. With this feature, we OpenShift could support assembling as root. Couldn't?

**Comment by mfojtik** [comment]
@ppisar they are not the namespaces we were hoping for, so we can't enable `root` user by default.
