### ISSUE TITLE
httpd log file /tmp_error log should be directed to STDERR

### ISSUE THREAD

**Issue by nhr** [openshift/sti-perl#72]
Presently we direct [some httpd logging to STDOUT](https://github.com/openshift/sti-perl/blob/master/5.20/contrib/etc/httpdconf.sed#L7), however we do not expose error messages in a similar fashion. This complicates the process of troubleshooting Perl applications, as most of the runtime errors are being sent to the error_log file.

**Comment by mfojtik** [comment]
both logs should log into stdout, this is a bug.

**Comment by rhcarvalho** [comment]
Looks like this applies to PHP as well...

- https://github.com/openshift/sti-perl/pull/53
- https://github.com/openshift/sti-php/pull/64

Shall we send both to `stdout`, or distinguish `stdout` / `stderr`?

```
s%^ErrorLog "logs/error_log"%ErrorLog "|/usr/bin/cat"%
s%CustomLog "logs/access_log"%CustomLog "|/usr/bin/cat"%
```

@php-coder including you here since you worked on this before.
@mfojtik @bparees @nhr @php-coder WDYT? I would prefer to distinguish the streams.

**Comment by php-coder** [comment]
I'm voting for distinguishing them too. Interesting to see how will you do this.

**Comment by mfojtik** [comment]
We can prefix them, I assume httpd allows to set custom formatter.

**Comment by bparees** [comment]
prefixing works for me.

**Comment by php-coder** [comment]
Ideally, is to have a real stdout/stderr differentiation, it allows to programmatically distinguish them (like this: https://github.com/docker/docker/issues/7440#issuecomment-51365165)

**Comment by php-coder** [comment]
I didn't try, but maybe the following would work:
```
s%^ErrorLog "logs/error_log"%ErrorLog "|perl -wlne 'print STDERR'"%
```

**Comment by ppisar** [comment]
On Mon, Feb 29, 2016 at 02:54:58AM -0800, Rodolfo Carvalho wrote:
> 
> Shall we send both to `stdout`, or distinguish `stdout` / `stderr`?
> 
No. Access log to stdout, error log to stderr. See run-httpd24.sh from
httpd24:

~~~~
sed -ri ' s!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g; s!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g;' /opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
~~~~

**Comment by php-coder** [comment]
P.S. I don't remember why I didn't use `/dev/stdout` and `/dev/stderr` here. If it works we could use them.

**Comment by ppisar** [comment]
It works for me when running "docker run" for the an application image without "-ti" arguments. Otherwise the "docker" tool merges containers stderr to "docker" tool stdout.

I hope the change will not bother users who got used to the log in the /tmp directory.  I believe the original plan was to volume-mount it, so that they can have logs stored permanently.

I will add test and send pull request. Here is the important change for those who want to try it:

{{{
--- a/5.20/contrib/etc/httpdconf.sed
+++ b/5.20/contrib/etc/httpdconf.sed
@@ -3,5 +3,5 @@ s/^User apache/User default/
 s/^Group apache/Group root/
 s%^DocumentRoot "/opt/rh/httpd24/root/var/www/html"%DocumentRoot "/opt/app-root/src"%
 s%^<Directory "/opt/rh/httpd24/root/var/html"%<Directory "/opt/app-root/src"%
-s%^ErrorLog "logs/error_log"%ErrorLog "/tmp/error_log"%
-s%CustomLog "logs/access_log"%CustomLog "|/usr/bin/cat"%
+s%^ErrorLog "logs/error_log"%ErrorLog "/proc/self/fd/2"%
+s%CustomLog "logs/access_log"%CustomLog "/proc/self/fd/1"%
}}}

**Comment by mfojtik** [comment]
@ppisar does the #73 fixes this issue?

**Comment by mfojtik** [comment]
@ppisar sorry, just read description. closing now.
